### ISSUE TITLE
Message Queues

### ISSUE THREAD

**Issue by dmit-ch** [Webiny/Framework#38]
Hi,

I just started working with Webiny Framework for a small test project of mine.

For two or more of my modules (Image Upload, Email Sending) I would like to go ahead with Message Queues. 

Do you have any plans on implementing such component in the Framework?
Or if I am about to implement my own Component, Bridge and Driver( RabbitMQ ), what would you suggest be the best way to do this?

**Comment by Pavel910** [comment]
Hi dmit-ch,

For now MessageQueueing is not on our TODO list, but if you are interested in developing the component yourself, I would gladly provide some help and will be available for questions from you.

1. A good place to start is a Mailer component - see how that component is structured.
2. Bridge will be a wrapper for your queueing service, ie. RabbitMQ (or any other): https://github.com/videlalvaro/php-amqplib (for example)
You don't even need a driver, just a bridge will be enough.
3. You need to create an Interface that all bridges will have to implement, just to make them switchable, and to provide nicer/unified naming for methods instead of those used by 3rd party libraries.
4. Main component class will use the bridge specified in the config of the component.

If you need some help feel free to ask it here.

**Comment by SvenAlHamad** [comment]
Closing this one due to inactivity.
